config:
  use_colors: true
  send_anonymous_usage_stats: False

default:
    target: dev
    outputs:
      dev:
        type: postgres
        threads: 8
        dbname: csgo
        schema: project_dev
        user: postgres
        password: postgres

        host: localhost # your Postgres host name
        port: 5432
        keepalives_idle: 0 # default 0, indicating the system default.
        connect_timeout: 10 # default 10 seconds
      prod:
        type: postgres
        threads: 8
        dbname: csgo
        schema: project_prod
        user: postgres
        password: postgres

        host: localhost # your Postgres host name
        port: 5432
        keepalives_idle: 0 # default 0, indicating the system default.
        connect_timeout: 10 # default 10 seconds
