from peewee import (
    BooleanField,
    CharField,
    DatabaseProxy,
    FloatField,
    IntegerField,
    Model,
)

database_proxy = DatabaseProxy()


class BaseModel(Model):
    class Meta:
        database = database_proxy


class Frames(BaseModel):
    class Meta:
        indexes = ((("matchID", "tick", "roundNum"), True),)

    ds = CharField(null=True)
    matchID = CharField(null=True)
    roundNum = IntegerField(null=True)
    tick = IntegerField(null=True)
    seconds = FloatField(null=True)
    ctTeamName = CharField(null=True)
    ctEqVal = IntegerField(null=True)
    ctAlivePlayers = IntegerField(null=True)
    ctUtility = IntegerField(null=True)
    tTeamName = CharField(null=True)
    tEqVal = IntegerField(null=True)
    tAlivePlayers = IntegerField(null=True)
    tUtility = IntegerField(null=True)


class Rounds(BaseModel):
    class Meta:
        indexes = ((("matchID", "startTick"), True),)

    ds = CharField(null=True)
    matchID = CharField(null=True)
    roundNum = IntegerField(null=True)
    mapName = CharField(null=True)
    startTick = IntegerField(null=True)
    freezeTimeEndTick = IntegerField(null=True)
    endTick = IntegerField(null=True)
    endOfficialTick = IntegerField(null=True)
    tScore = IntegerField(null=True)
    ctScore = IntegerField(null=True)
    endTScore = IntegerField(null=True)
    endCTScore = IntegerField(null=True)
    tTeam = CharField(null=True)
    ctTeam = CharField(null=True)
    winningSide = CharField(null=True)
    winningTeam = CharField(null=True)
    losingTeam = CharField(null=True)
    roundEndReason = CharField(null=True)
    ctFreezeTimeEndEqVal = IntegerField(null=True)
    ctRoundStartEqVal = IntegerField(null=True)
    ctRoundSpendMoney = IntegerField(null=True)
    ctBuyType = CharField(null=True)
    tFreezeTimeEndEqVal = IntegerField(null=True)
    tRoundStartEqVal = IntegerField(null=True)
    tRoundSpendMoney = IntegerField(null=True)
    tBuyType = CharField(null=True)


class Kills(BaseModel):
    class Meta:
        indexes = ((("matchID", "tick", "mapName"), True),)

    ds = CharField(null=True)
    matchID = CharField(null=True)
    tick = IntegerField(null=True)
    seconds = FloatField(null=True)
    clockTime = CharField(null=True)
    attackerSteamID = CharField(null=True)
    attackerName = CharField(null=True)
    attackerTeam = CharField(null=True)
    attackerSide = CharField(null=True)
    attackerX = FloatField(null=True)
    attackerY = FloatField(null=True)
    attackerZ = FloatField(null=True)
    attackerViewX = FloatField(null=True)
    attackerViewY = FloatField(null=True)
    victimSteamID = CharField(null=True)
    victimName = CharField(null=True)
    victimTeam = CharField(null=True)
    victimSide = CharField(null=True)
    victimX = FloatField(null=True)
    victimY = FloatField(null=True)
    victimZ = FloatField(null=True)
    victimViewX = FloatField(null=True)
    victimViewY = FloatField(null=True)
    assisterSteamID = CharField(null=True)
    assisterName = CharField(null=True)
    assisterTeam = CharField(null=True)
    assisterSide = CharField(null=True)
    isSuicide = BooleanField()
    isTeamkill = BooleanField()
    isWallbang = BooleanField()
    penetratedObjects = IntegerField(null=True)
    isFirstKill = BooleanField()
    isHeadshot = BooleanField()
    victimBlinded = BooleanField()
    attackerBlinded = BooleanField()
    flashThrowerSteamID = CharField(null=True)
    flashThrowerName = CharField(null=True)
    flashThrowerTeam = CharField(null=True)
    flashThrowerSide = CharField(null=True)
    noScope = BooleanField()
    thruSmoke = BooleanField()
    distance = FloatField(null=True)
    isTrade = BooleanField()
    playerTradedName = CharField(null=True)
    playerTradedTeam = CharField(null=True)
    playerTradedSteamID = CharField(null=True)
    playerTradedSide = CharField(null=True)
    weapon = CharField(null=True)
    weaponClass = CharField(null=True)
    roundNum = IntegerField(null=True)
    mapName = CharField(null=True)


class Damages(BaseModel):
    class Meta:
        indexes = ((("matchID", "tick", "mapName"), True),)

    ds = CharField(null=True)
    tick = IntegerField(null=True)
    seconds = FloatField(null=True)
    clockTime = CharField(null=True)
    attackerSteamID = CharField(null=True)
    attackerName = CharField(null=True)
    attackerTeam = CharField(null=True)
    attackerSide = CharField(null=True)
    attackerX = FloatField(null=True)
    attackerY = FloatField(null=True)
    attackerZ = FloatField(null=True)
    attackerViewX = FloatField(null=True)
    attackerViewY = FloatField(null=True)
    attackerStrafe = FloatField(null=True)
    victimSteamID = CharField(null=True)
    victimName = CharField(null=True)
    victimTeam = CharField(null=True)
    victimSide = CharField(null=True)
    victimX = FloatField(null=True)
    victimY = FloatField(null=True)
    victimZ = FloatField(null=True)
    victimViewX = FloatField(null=True)
    victimViewY = FloatField(null=True)
    weapon = CharField(null=True)
    weaponClass = CharField(null=True)
    hpDamage = IntegerField(null=True)
    hpDamageTaken = IntegerField(null=True)
    armorDamage = IntegerField(null=True)
    armorDamageTaken = IntegerField(null=True)
    hitGroup = CharField(null=True)
    isFriendlyFire = BooleanField()
    distance = FloatField(null=True)
    zoomLevel = IntegerField(null=True)
    roundNum = IntegerField(null=True)
    matchID = CharField(null=True)
    mapName = CharField(null=True)


class Grenades(BaseModel):
    class Meta:
        indexes = ((("matchID", "throwTick", "mapName"), True),)

    ds = CharField(null=True)
    throwTick = IntegerField(null=True)
    destroyTick = IntegerField(null=True)
    throwSeconds = FloatField(null=True)
    throwClockTime = CharField(null=True)
    destroySeconds = FloatField(null=True)
    destroyClockTime = CharField(null=True)
    throwerSteamID = CharField(null=True)
    throwerName = CharField(null=True)
    throwerTeam = CharField(null=True)
    throwerSide = CharField(null=True)
    throwerX = FloatField(null=True)
    throwerY = FloatField(null=True)
    throwerZ = FloatField(null=True)
    grenadeType = CharField(null=True)
    grenadeX = FloatField(null=True)
    grenadeY = FloatField(null=True)
    grenadeZ = FloatField(null=True)
    entityId = CharField(null=True)
    roundNum = IntegerField(null=True)
    matchID = CharField(null=True)
    mapName = CharField(null=True)


class Flashes(BaseModel):
    class Meta:
        indexes = ((("matchID", "tick", "mapName"), True),)

    tick = IntegerField(null=True)
    ds = CharField(null=True)
    seconds = FloatField(null=True)
    clockTime = CharField(null=True)
    attackerSteamID = CharField(null=True)
    attackerName = CharField(null=True)
    attackerTeam = CharField(null=True)
    attackerSide = CharField(null=True)
    attackerX = FloatField(null=True)
    attackerY = FloatField(null=True)
    attackerZ = FloatField(null=True)
    attackerViewX = FloatField(null=True)
    attackerViewY = FloatField(null=True)
    playerSteamID = CharField(null=True)
    playerName = CharField(null=True)
    playerTeam = CharField(null=True)
    playerSide = CharField(null=True)
    playerX = FloatField(null=True)
    playerY = FloatField(null=True)
    playerZ = FloatField(null=True)
    playerViewX = FloatField(null=True)
    playerViewY = FloatField(null=True)
    flashDuration = FloatField(null=True)
    roundNum = IntegerField(null=True)
    matchID = CharField(null=True)
    mapName = CharField(null=True)


class WeaponFires(BaseModel):
    class Meta:
        indexes = ((("matchID", "tick", "playerSteamID", "mapName"), True),)

    tick = IntegerField(null=True)
    ds = CharField(null=True)
    seconds = FloatField(null=True)
    clockTime = CharField(null=True)
    playerSteamID = CharField(null=True)
    playerName = CharField(null=True)
    playerTeam = CharField(null=True)
    playerSide = CharField(null=True)
    playerX = FloatField(null=True)
    playerY = FloatField(null=True)
    playerZ = FloatField(null=True)
    playerViewX = FloatField(null=True)
    playerViewY = FloatField(null=True)
    playerStrafe = FloatField(null=True)
    weapon = CharField(null=True)
    weaponClass = CharField(null=True)
    ammoInMagazine = IntegerField(null=True)
    ammoInReserve = IntegerField(null=True)
    zoomLevel = IntegerField(null=True)
    roundNum = IntegerField(null=True)
    matchID = CharField(null=True)
    mapName = CharField(null=True)


class BombEvents(BaseModel):
    class Meta:
        indexes = ((("matchID", "tick", "mapName"), True),)

    tick = IntegerField(null=True)
    seconds = FloatField(null=True)
    clockTime = CharField(null=True)
    ds = CharField(null=True)
    playerSteamID = CharField(null=True)
    playerName = CharField(null=True)
    playerTeam = CharField(null=True)
    playerX = FloatField(null=True)
    playerY = FloatField(null=True)
    playerZ = FloatField(null=True)
    bombAction = CharField(null=True)
    bombSite = CharField(null=True)
    roundNum = IntegerField(null=True)
    matchID = CharField(null=True)
    mapName = CharField(null=True)


class PlayerFrames(BaseModel):
    class Meta:
        indexes = ((("matchID", "tick", "mapName"), True),)

    roundNum = IntegerField(null=True)
    tick = IntegerField(null=True)
    seconds = FloatField(null=True)
    side = CharField(null=True)
    ds = CharField(null=True)
    teamName = CharField(null=True)
    steamID = CharField(null=True)
    name = CharField(null=True)
    team = CharField(null=True)
    x = FloatField(null=True)
    y = FloatField(null=True)
    z = FloatField(null=True)
    eyeX = FloatField(null=True)
    eyeY = FloatField(null=True)
    eyeZ = FloatField(null=True)
    velocityX = FloatField(null=True)
    velocityY = FloatField(null=True)
    velocityZ = FloatField(null=True)
    viewX = FloatField(null=True)
    viewY = FloatField(null=True)
    hp = IntegerField(null=True)
    armor = IntegerField(null=True)
    activeWeapon = CharField(null=True)
    flashGrenades = IntegerField(null=True)
    smokeGrenades = IntegerField(null=True)
    heGrenades = IntegerField(null=True)
    fireGrenades = IntegerField(null=True)
    totalUtility = IntegerField(null=True)
    lastPlaceName = CharField(null=True)
    isAlive = BooleanField()
    isBot = BooleanField()
    isBlinded = BooleanField()
    isAirborne = BooleanField()
    isDucking = BooleanField()
    isDuckingInProgress = BooleanField()
    isUnDuckingInProgress = BooleanField()
    isDefusing = BooleanField()
    isPlanting = BooleanField()
    isReloading = BooleanField()
    isInBombZone = BooleanField()
    isInBuyZone = BooleanField()
    isStanding = BooleanField()
    isScoped = BooleanField()
    isWalking = BooleanField()
    isUnknown = BooleanField()
    spotters = CharField(null=True)
    equipmentValue = IntegerField(null=True)
    equipmentValueFreezetimeEnd = IntegerField(null=True)
    equipmentValueRoundStart = IntegerField(null=True)
    cash = IntegerField(null=True)
    cashSpendThisRound = IntegerField(null=True)
    cashSpendTotal = IntegerField(null=True)
    hasHelmet = BooleanField()
    hasDefuse = BooleanField()
    hasBomb = BooleanField()
    ping = IntegerField(null=True)
    zoomLevel = IntegerField(null=True)
    matchID = CharField(null=True)
    mapName = CharField(null=True)
